### ISSUE TITLE
AllocateEipAddressAndAttachToInstance.yml不能指定eip的线路类型

### ISSUE THREAD

**Issue by hrool** [aliyun/oos-templates#6]
文件: CloudProductActions/ECS/YAML/ACS::ECS::AllocateEipAddressAndAttachToInstance.yml
在使用的时候,我需要加申请线路类型为bgp_pro的eip, 按照这个actions没法完成, 建议更新一下
建议加一个
```
Parameters:
  isp:
    Label:
      en: EIP  line type
      zh-cn: EIP的线路类型
    Type: String
    AllowedValues:
      - BGP
      - BGP_PRO
    Default: BGP
```
```
Tasks:
  - Name: allocateEipAddress
    Action: 'ACS::ExecuteAPI'
    Description:
      en: Allocates an EIP
      zh-cn: 获取一个弹性公网IP
    Properties:
      Service: ECS
      API: AllocateEipAddress
      Parameters:
        RegionId: '{{ regionId }}'
        InternetChargeType: '{{ internetChargeType }}'
        Bandwidth: '{{ bandwidth }}'
        ISP: '{{ isp }}'
    Outputs:
      allocationId:
        Type: String
        ValueSelector: .AllocationId
```
